### ISSUE TITLE
run_mydata_new.py error

### ISSUE THREAD

**Issue by elixtang** [wyshi/user-simulator#5]
Traceback (most recent call last):
  File "/Users/work/user-simulator/run_mydata_new.py", line 4, in <module>
    from rl.policy_model import Net
  File "/Users/work/user-simulator/rl/policy_model.py", line 6, in <module>
    from simulator.nlu_model.data_preprocess import DataProcessor, l2_matrix_norm, AverageMeter, print_cm, eval_
  File "/Users/work/user-simulator/simulator/nlu_model/data_preprocess.py", line 23, in <module>
    from simulator.nlu_model.nlu_config import Config
  File "/Users/work/user-simulator/simulator/nlu_model/nlu_config.py", line 4, in <module>
    class Config():
  File "/Users/work/user-simulator/simulator/nlu_model/nlu_config.py", line 21, in Config
    with open('/home/wyshi/simulator/data/multiwoz-master/data/multi-woz/nlu/labelEncoder.pkl', 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wyshi/simulator/data/multiwoz-master/data/multi-woz/nlu/labelEncoder.pkl'

---------------

**Comment by jin8** [comment]
Were you  able to solve this problem labelEncoder.pkl ?? I cannot find this file in the github.

**Comment by wyshi** [comment]
Hello sorry about the delay. I just uploaded the .pkl file
